"""Add specialization column to doctors table

Revision ID: ff0eb5d276ba
Revises: 
Create Date: 2024-06-13 10:26:20.417003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0eb5d276ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialization', sa.String(), nullable=False, server_default='General'))
    # ### end Alembic commands ###

    with op.batch_alter_table('doctors') as batch_op:
        batch_op.alter_column('specialization', server_default=None)
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'specialization')
    # ### end Alembic commands ###
